#
# Basis for Minimum Docker image to build Android AOSP using Ubuntu 16.04
#
FROM ubuntu:16.04

MAINTAINER Jared Hulbert <jaredeh@gmail.com>

# /bin/sh points to Dash by default, reconfigure to use bash until Android
# build becomes POSIX compliant
RUN echo "dash dash/sh boolean false" | debconf-set-selections && \
    dpkg-reconfigure -p critical dash

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      openjdk-8-jdk  && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      build-essential  && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
      x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils \
      libssl-dev libbz2-dev libbz2-1.0 libghc-bzlib-dev liblz4-tool libc6-dev \
      linux-libc-dev g++-5-multilib && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      git-core gnupg flex bison xsltproc openssl gperf zip curl unzip ccache bc \
      automake lzop python-networkx bzip2 squashfs-tools pngcrush schedtool sudo \
      dpkg-dev optipng maven vim-common cgpt util-linux cpio \
      software-properties-common && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      python3.6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN wget https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz && \
    tar -xvzf go-ipfs_v0.7.0_linux-amd64.tar.gz && \
    cd go-ipfs; sudo bash install.sh; cd .. && \
    rm -rf go-ipfs_v0.7.0_linux-amd64.tar.gz && \
    rm -rf go-ipfs
